services: 
  database: 
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: 
      - "${DB_PORT}:5432"
    volumes:
    - ./database/:/docker-entrypoint-initdb.d/
    - psql_volume:/var/lib/postgresql/data
    
volumes:
  psql_volume:
    driver: local